pathbase = "/home/vinicius/dev-projects/java/unisinos/tcc/app-leitura-agrup-arq-resultados/output-processing"

stb <- read.csv(file = paste(pathbase, "stb.csv", sep = "/"), header = TRUE, sep = ";")
summary(stb, mean, na.rm=TRUE)
sd(stb$effort_svn)
sd(stb$effort_git)
wilcox.test(stb$effort_git, stb$effort_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(stb$effort_git, stb$effort_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(stb$percentageOfChange_git, stb$percentageOfChange_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(stb$percentageOfChange_git, stb$percentageOfChange_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(stb$accuracy_git, stb$accuracy_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(stb$accuracy_git, stb$accuracy_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(stb$precision_git, stb$precision_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(stb$precision_git, stb$precision_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(stb$recall_git, stb$recall_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(stb$recall_git, stb$recall_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(stb$measure_git, stb$measure_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(stb$measure_git, stb$measure_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)


magisk <- read.csv(file = paste(pathbase, "Magisk.csv", sep = "/"), header = TRUE, sep = ";")
summary(magisk, mean, na.rm=TRUE)
sd(magisk$effort_svn)
sd(magisk$effort_git)
wilcox.test(magisk$effort_git, magisk$effort_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(magisk$effort_git, magisk$effort_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(magisk$percentageOfChange_git, magisk$percentageOfChange_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(magisk$percentageOfChange_git, magisk$percentageOfChange_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(magisk$accuracy_git, magisk$accuracy_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(magisk$accuracy_git, magisk$accuracy_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(magisk$precision_git, magisk$precision_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(magisk$precision_git, magisk$precision_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(magisk$recall_git, magisk$recall_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(magisk$recall_git, magisk$recall_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(magisk$measure_git, magisk$measure_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(magisk$measure_git, magisk$measure_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)


rxjava <- read.csv(file = paste(pathbase, "RxJava.csv", sep = "/"), header = TRUE, sep = ";")
summary(rxjava, mean, na.rm=TRUE)
sd(rxjava$effort_svn)
sd(rxjava$effort_git)
wilcox.test(rxjava$effort_git, rxjava$effort_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(rxjava$effort_git, rxjava$effort_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(rxjava$percentageOfChange_git, rxjava$percentageOfChange_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(rxjava$percentageOfChange_git, rxjava$percentageOfChange_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(rxjava$accuracy_git, rxjava$accuracy_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(rxjava$accuracy_git, rxjava$accuracy_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(rxjava$precision_git, rxjava$precision_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(rxjava$precision_git, rxjava$precision_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(rxjava$recall_git, rxjava$recall_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(rxjava$recall_git, rxjava$recall_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(rxjava$measure_git, rxjava$measure_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(rxjava$measure_git, rxjava$measure_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)


ant_design <- read.csv(file = paste(pathbase, "ant-design.csv", sep = "/"), header = TRUE, sep = ";")
summary(ant_design, mean, na.rm=TRUE)
sd(ant_design$effort_svn)
sd(ant_design$effort_git)
wilcox.test(ant_design$effort_git, ant_design$effort_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(ant_design$effort_git, ant_design$effort_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(ant_design$percentageOfChange_git, ant_design$percentageOfChange_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(ant_design$percentageOfChange_git, ant_design$percentageOfChange_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(ant_design$accuracy_git, ant_design$accuracy_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(ant_design$accuracy_git, ant_design$accuracy_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(ant_design$precision_git, ant_design$precision_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(ant_design$precision_git, ant_design$precision_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(ant_design$recall_git, ant_design$recall_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(ant_design$recall_git, ant_design$recall_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(ant_design$measure_git, ant_design$measure_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(ant_design$measure_git, ant_design$measure_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)


axios <- read.csv(file = paste(pathbase, "axios.csv", sep = "/"), header = TRUE, sep = ";")
summary(axios, mean, na.rm=TRUE)
sd(axios$effort_svn)
sd(axios$effort_git)
wilcox.test(axios$effort_git, axios$effort_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(axios$effort_git, axios$effort_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(axios$percentageOfChange_git, axios$percentageOfChange_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(axios$percentageOfChange_git, axios$percentageOfChange_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(axios$accuracy_git, axios$accuracy_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(axios$accuracy_git, axios$accuracy_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(axios$precision_git, axios$precision_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(axios$precision_git, axios$precision_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(axios$recall_git, axios$recall_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(axios$recall_git, axios$recall_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(axios$measure_git, axios$measure_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(axios$measure_git, axios$measure_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)


bitcoin <- read.csv(file = paste(pathbase, "bitcoin.csv", sep = "/"), header = TRUE, sep = ";")
summary(bitcoin, mean, na.rm=TRUE)
sd(bitcoin$effort_svn)
sd(bitcoin$effort_git)
wilcox.test(bitcoin$effort_git, bitcoin$effort_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(bitcoin$effort_git, bitcoin$effort_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(bitcoin$percentageOfChange_git, bitcoin$percentageOfChange_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(bitcoin$percentageOfChange_git, bitcoin$percentageOfChange_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(bitcoin$accuracy_git, bitcoin$accuracy_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(bitcoin$accuracy_git, bitcoin$accuracy_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(bitcoin$precision_git, bitcoin$precision_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(bitcoin$precision_git, bitcoin$precision_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(bitcoin$recall_git, bitcoin$recall_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(bitcoin$recall_git, bitcoin$recall_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(bitcoin$measure_git, bitcoin$measure_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(bitcoin$measure_git, bitcoin$measure_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)


bootstrap <- read.csv(file = paste(pathbase, "bootstrap.csv", sep = "/"), header = TRUE, sep = ";")
summary(bootstrap, mean, na.rm=TRUE)
sd(bootstrap$effort_svn)
sd(bootstrap$effort_git)
wilcox.test(bootstrap$effort_git, bootstrap$effort_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(bootstrap$effort_git, bootstrap$effort_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(bootstrap$percentageOfChange_git, bootstrap$percentageOfChange_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(bootstrap$percentageOfChange_git, bootstrap$percentageOfChange_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(bootstrap$accuracy_git, bootstrap$accuracy_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(bootstrap$accuracy_git, bootstrap$accuracy_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(bootstrap$precision_git, bootstrap$precision_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(bootstrap$precision_git, bootstrap$precision_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(bootstrap$recall_git, bootstrap$recall_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(bootstrap$recall_git, bootstrap$recall_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(bootstrap$measure_git, bootstrap$measure_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(bootstrap$measure_git, bootstrap$measure_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)


caffe <- read.csv(file = paste(pathbase, "caffe.csv", sep = "/"), header = TRUE, sep = ";")
summary(caffe, mean, na.rm=TRUE)
sd(caffe$effort_svn)
sd(caffe$effort_git)
wilcox.test(caffe$effort_git, caffe$effort_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(caffe$effort_git, caffe$effort_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(caffe$percentageOfChange_git, caffe$percentageOfChange_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(caffe$percentageOfChange_git, caffe$percentageOfChange_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(caffe$accuracy_git, caffe$accuracy_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(caffe$accuracy_git, caffe$accuracy_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(caffe$precision_git, caffe$precision_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(caffe$precision_git, caffe$precision_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(caffe$recall_git, caffe$recall_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(caffe$recall_git, caffe$recall_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(caffe$measure_git, caffe$measure_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(caffe$measure_git, caffe$measure_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)


code_server <- read.csv(file = paste(pathbase, "code-server.csv", sep = "/"), header = TRUE, sep = ";")
summary(code_server, mean, na.rm=TRUE)
sd(code_server$effort_svn)
sd(code_server$effort_git)
wilcox.test(code_server$effort_git, code_server$effort_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(code_server$effort_git, code_server$effort_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(code_server$percentageOfChange_git, code_server$percentageOfChange_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(code_server$percentageOfChange_git, code_server$percentageOfChange_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(code_server$accuracy_git, code_server$accuracy_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(code_server$accuracy_git, code_server$accuracy_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(code_server$precision_git, code_server$precision_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(code_server$precision_git, code_server$precision_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(code_server$recall_git, code_server$recall_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(code_server$recall_git, code_server$recall_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(code_server$measure_git, code_server$measure_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(code_server$measure_git, code_server$measure_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)


core <- read.csv(file = paste(pathbase, "core.csv", sep = "/"), header = TRUE, sep = ";")
summary(core, mean, na.rm=TRUE)
sd(core$effort_svn)
sd(core$effort_git)
wilcox.test(core$effort_git, core$effort_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(core$effort_git, core$effort_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(core$percentageOfChange_git, core$percentageOfChange_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(core$percentageOfChange_git, core$percentageOfChange_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(core$accuracy_git, core$accuracy_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(core$accuracy_git, core$accuracy_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(core$precision_git, core$precision_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(core$precision_git, core$precision_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(core$recall_git, core$recall_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(core$recall_git, core$recall_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(core$measure_git, core$measure_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(core$measure_git, core$measure_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)


django <- read.csv(file = paste(pathbase, "django.csv", sep = "/"), header = TRUE, sep = ";")
summary(django, mean, na.rm=TRUE)
sd(django$effort_svn)
sd(django$effort_git)
wilcox.test(django$effort_git, django$effort_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(django$effort_git, django$effort_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(django$percentageOfChange_git, django$percentageOfChange_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(django$percentageOfChange_git, django$percentageOfChange_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(django$accuracy_git, django$accuracy_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(django$accuracy_git, django$accuracy_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(django$precision_git, django$precision_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(django$precision_git, django$precision_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(django$recall_git, django$recall_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(django$recall_git, django$recall_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(django$measure_git, django$measure_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(django$measure_git, django$measure_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)


dubbo <- read.csv(file = paste(pathbase, "dubbo.csv", sep = "/"), header = TRUE, sep = ";")
summary(dubbo, mean, na.rm=TRUE)
sd(dubbo$effort_svn)
sd(dubbo$effort_git)
wilcox.test(dubbo$effort_git, dubbo$effort_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(dubbo$effort_git, dubbo$effort_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(dubbo$percentageOfChange_git, dubbo$percentageOfChange_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(dubbo$percentageOfChange_git, dubbo$percentageOfChange_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(dubbo$accuracy_git, dubbo$accuracy_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(dubbo$accuracy_git, dubbo$accuracy_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(dubbo$precision_git, dubbo$precision_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(dubbo$precision_git, dubbo$precision_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(dubbo$recall_git, dubbo$recall_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(dubbo$recall_git, dubbo$recall_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(dubbo$measure_git, dubbo$measure_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(dubbo$measure_git, dubbo$measure_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)


electron <- read.csv(file = paste(pathbase, "electron.csv", sep = "/"), header = TRUE, sep = ";")
summary(electron, mean, na.rm=TRUE)
sd(electron$effort_svn)
sd(electron$effort_git)
wilcox.test(electron$effort_git, electron$effort_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(electron$effort_git, electron$effort_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(electron$percentageOfChange_git, electron$percentageOfChange_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(electron$percentageOfChange_git, electron$percentageOfChange_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(electron$accuracy_git, electron$accuracy_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(electron$accuracy_git, electron$accuracy_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(electron$precision_git, electron$precision_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(electron$precision_git, electron$precision_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(electron$recall_git, electron$recall_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(electron$recall_git, electron$recall_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(electron$measure_git, electron$measure_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(electron$measure_git, electron$measure_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)


emscripten <- read.csv(file = paste(pathbase, "emscripten.csv", sep = "/"), header = TRUE, sep = ";")
summary(emscripten, mean, na.rm=TRUE)
sd(emscripten$effort_svn)
sd(emscripten$effort_git)
wilcox.test(emscripten$effort_git, emscripten$effort_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(emscripten$effort_git, emscripten$effort_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(emscripten$percentageOfChange_git, emscripten$percentageOfChange_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(emscripten$percentageOfChange_git, emscripten$percentageOfChange_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(emscripten$accuracy_git, emscripten$accuracy_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(emscripten$accuracy_git, emscripten$accuracy_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(emscripten$precision_git, emscripten$precision_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(emscripten$precision_git, emscripten$precision_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(emscripten$recall_git, emscripten$recall_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(emscripten$recall_git, emscripten$recall_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(emscripten$measure_git, emscripten$measure_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(emscripten$measure_git, emscripten$measure_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)


faceswap <- read.csv(file = paste(pathbase, "faceswap.csv", sep = "/"), header = TRUE, sep = ";")
summary(faceswap, mean, na.rm=TRUE)
sd(faceswap$effort_svn)
sd(faceswap$effort_git)
wilcox.test(faceswap$effort_git, faceswap$effort_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(faceswap$effort_git, faceswap$effort_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(faceswap$percentageOfChange_git, faceswap$percentageOfChange_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(faceswap$percentageOfChange_git, faceswap$percentageOfChange_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(faceswap$accuracy_git, faceswap$accuracy_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(faceswap$accuracy_git, faceswap$accuracy_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(faceswap$precision_git, faceswap$precision_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(faceswap$precision_git, faceswap$precision_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(faceswap$recall_git, faceswap$recall_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(faceswap$recall_git, faceswap$recall_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(faceswap$measure_git, faceswap$measure_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(faceswap$measure_git, faceswap$measure_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)


flask <- read.csv(file = paste(pathbase, "flask.csv", sep = "/"), header = TRUE, sep = ";")
summary(flask, mean, na.rm=TRUE)
sd(flask$effort_svn)
sd(flask$effort_git)
wilcox.test(flask$effort_git, flask$effort_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(flask$effort_git, flask$effort_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(flask$percentageOfChange_git, flask$percentageOfChange_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(flask$percentageOfChange_git, flask$percentageOfChange_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(flask$accuracy_git, flask$accuracy_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(flask$accuracy_git, flask$accuracy_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(flask$precision_git, flask$precision_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(flask$precision_git, flask$precision_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(flask$recall_git, flask$recall_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(flask$recall_git, flask$recall_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(flask$measure_git, flask$measure_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(flask$measure_git, flask$measure_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)


googletest <- read.csv(file = paste(pathbase, "googletest.csv", sep = "/"), header = TRUE, sep = ";")
summary(googletest, mean, na.rm=TRUE)
sd(googletest$effort_svn)
sd(googletest$effort_git)
wilcox.test(googletest$effort_git, googletest$effort_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(googletest$effort_git, googletest$effort_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(googletest$percentageOfChange_git, googletest$percentageOfChange_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(googletest$percentageOfChange_git, googletest$percentageOfChange_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(googletest$accuracy_git, googletest$accuracy_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(googletest$accuracy_git, googletest$accuracy_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(googletest$precision_git, googletest$precision_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(googletest$precision_git, googletest$precision_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(googletest$recall_git, googletest$recall_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(googletest$recall_git, googletest$recall_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(googletest$measure_git, googletest$measure_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(googletest$measure_git, googletest$measure_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)


hashcat <- read.csv(file = paste(pathbase, "hashcat.csv", sep = "/"), header = TRUE, sep = ";")
summary(hashcat, mean, na.rm=TRUE)
sd(hashcat$effort_svn)
sd(hashcat$effort_git)
wilcox.test(hashcat$effort_git, hashcat$effort_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(hashcat$effort_git, hashcat$effort_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(hashcat$percentageOfChange_git, hashcat$percentageOfChange_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(hashcat$percentageOfChange_git, hashcat$percentageOfChange_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(hashcat$accuracy_git, hashcat$accuracy_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(hashcat$accuracy_git, hashcat$accuracy_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(hashcat$precision_git, hashcat$precision_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(hashcat$precision_git, hashcat$precision_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(hashcat$recall_git, hashcat$recall_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(hashcat$recall_git, hashcat$recall_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(hashcat$measure_git, hashcat$measure_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(hashcat$measure_git, hashcat$measure_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)


hibernate_orm <- read.csv(file = paste(pathbase, "hibernate-orm.csv", sep = "/"), header = TRUE, sep = ";")
summary(hibernate_orm, mean, na.rm=TRUE)
sd(hibernate_orm$effort_svn)
sd(hibernate_orm$effort_git)
wilcox.test(hibernate_orm$effort_git, hibernate_orm$effort_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(hibernate_orm$effort_git, hibernate_orm$effort_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(hibernate_orm$percentageOfChange_git, hibernate_orm$percentageOfChange_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(hibernate_orm$percentageOfChange_git, hibernate_orm$percentageOfChange_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(hibernate_orm$accuracy_git, hibernate_orm$accuracy_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(hibernate_orm$accuracy_git, hibernate_orm$accuracy_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(hibernate_orm$precision_git, hibernate_orm$precision_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(hibernate_orm$precision_git, hibernate_orm$precision_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(hibernate_orm$recall_git, hibernate_orm$recall_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(hibernate_orm$recall_git, hibernate_orm$recall_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(hibernate_orm$measure_git, hibernate_orm$measure_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(hibernate_orm$measure_git, hibernate_orm$measure_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)


jq <- read.csv(file = paste(pathbase, "jq.csv", sep = "/"), header = TRUE, sep = ";")
summary(jq, mean, na.rm=TRUE)
sd(jq$effort_svn)
sd(jq$effort_git)
wilcox.test(jq$effort_git, jq$effort_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(jq$effort_git, jq$effort_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(jq$percentageOfChange_git, jq$percentageOfChange_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(jq$percentageOfChange_git, jq$percentageOfChange_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(jq$accuracy_git, jq$accuracy_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(jq$accuracy_git, jq$accuracy_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(jq$precision_git, jq$precision_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(jq$precision_git, jq$precision_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(jq$recall_git, jq$recall_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(jq$recall_git, jq$recall_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(jq$measure_git, jq$measure_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(jq$measure_git, jq$measure_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)


jquery <- read.csv(file = paste(pathbase, "jquery.csv", sep = "/"), header = TRUE, sep = ";")
summary(jquery, mean, na.rm=TRUE)
sd(jquery$effort_svn)
sd(jquery$effort_git)
wilcox.test(jquery$effort_git, jquery$effort_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(jquery$effort_git, jquery$effort_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(jquery$percentageOfChange_git, jquery$percentageOfChange_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(jquery$percentageOfChange_git, jquery$percentageOfChange_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(jquery$accuracy_git, jquery$accuracy_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(jquery$accuracy_git, jquery$accuracy_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(jquery$precision_git, jquery$precision_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(jquery$precision_git, jquery$precision_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(jquery$recall_git, jquery$recall_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(jquery$recall_git, jquery$recall_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(jquery$measure_git, jquery$measure_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(jquery$measure_git, jquery$measure_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)


json <- read.csv(file = paste(pathbase, "json.csv", sep = "/"), header = TRUE, sep = ";")
summary(json, mean, na.rm=TRUE)
sd(json$effort_svn)
sd(json$effort_git)
wilcox.test(json$effort_git, json$effort_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(json$effort_git, json$effort_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(json$percentageOfChange_git, json$percentageOfChange_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(json$percentageOfChange_git, json$percentageOfChange_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(json$accuracy_git, json$accuracy_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(json$accuracy_git, json$accuracy_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(json$precision_git, json$precision_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(json$precision_git, json$precision_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(json$recall_git, json$recall_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(json$recall_git, json$recall_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(json$measure_git, json$measure_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(json$measure_git, json$measure_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)


junit5 <- read.csv(file = paste(pathbase, "junit5.csv", sep = "/"), header = TRUE, sep = ";")
summary(junit5, mean, na.rm=TRUE)
sd(junit5$effort_svn)
sd(junit5$effort_git)
wilcox.test(junit5$effort_git, junit5$effort_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(junit5$effort_git, junit5$effort_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(junit5$percentageOfChange_git, junit5$percentageOfChange_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(junit5$percentageOfChange_git, junit5$percentageOfChange_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(junit5$accuracy_git, junit5$accuracy_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(junit5$accuracy_git, junit5$accuracy_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(junit5$precision_git, junit5$precision_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(junit5$precision_git, junit5$precision_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(junit5$recall_git, junit5$recall_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(junit5$recall_git, junit5$recall_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(junit5$measure_git, junit5$measure_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(junit5$measure_git, junit5$measure_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)


keras <- read.csv(file = paste(pathbase, "keras.csv", sep = "/"), header = TRUE, sep = ";")
summary(keras, mean, na.rm=TRUE)
sd(keras$effort_svn)
sd(keras$effort_git)
wilcox.test(keras$effort_git, keras$effort_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(keras$effort_git, keras$effort_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(keras$percentageOfChange_git, keras$percentageOfChange_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(keras$percentageOfChange_git, keras$percentageOfChange_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(keras$accuracy_git, keras$accuracy_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(keras$accuracy_git, keras$accuracy_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(keras$precision_git, keras$precision_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(keras$precision_git, keras$precision_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(keras$recall_git, keras$recall_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(keras$recall_git, keras$recall_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(keras$measure_git, keras$measure_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(keras$measure_git, keras$measure_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)


libuv <- read.csv(file = paste(pathbase, "libuv.csv", sep = "/"), header = TRUE, sep = ";")
summary(libuv, mean, na.rm=TRUE)
sd(libuv$effort_svn)
sd(libuv$effort_git)
wilcox.test(libuv$effort_git, libuv$effort_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(libuv$effort_git, libuv$effort_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(libuv$percentageOfChange_git, libuv$percentageOfChange_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(libuv$percentageOfChange_git, libuv$percentageOfChange_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(libuv$accuracy_git, libuv$accuracy_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(libuv$accuracy_git, libuv$accuracy_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(libuv$precision_git, libuv$precision_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(libuv$precision_git, libuv$precision_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(libuv$recall_git, libuv$recall_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(libuv$recall_git, libuv$recall_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(libuv$measure_git, libuv$measure_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(libuv$measure_git, libuv$measure_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)


lombok <- read.csv(file = paste(pathbase, "lombok.csv", sep = "/"), header = TRUE, sep = ";")
summary(lombok, mean, na.rm=TRUE)
sd(lombok$effort_svn)
sd(lombok$effort_git)
wilcox.test(lombok$effort_git, lombok$effort_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(lombok$effort_git, lombok$effort_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(lombok$percentageOfChange_git, lombok$percentageOfChange_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(lombok$percentageOfChange_git, lombok$percentageOfChange_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(lombok$accuracy_git, lombok$accuracy_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(lombok$accuracy_git, lombok$accuracy_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(lombok$precision_git, lombok$precision_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(lombok$precision_git, lombok$precision_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(lombok$recall_git, lombok$recall_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(lombok$recall_git, lombok$recall_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(lombok$measure_git, lombok$measure_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(lombok$measure_git, lombok$measure_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)


mockito <- read.csv(file = paste(pathbase, "mockito.csv", sep = "/"), header = TRUE, sep = ";")
summary(mockito, mean, na.rm=TRUE)
sd(mockito$effort_svn)
sd(mockito$effort_git)
wilcox.test(mockito$effort_git, mockito$effort_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(mockito$effort_git, mockito$effort_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(mockito$percentageOfChange_git, mockito$percentageOfChange_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(mockito$percentageOfChange_git, mockito$percentageOfChange_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(mockito$accuracy_git, mockito$accuracy_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(mockito$accuracy_git, mockito$accuracy_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(mockito$precision_git, mockito$precision_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(mockito$precision_git, mockito$precision_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(mockito$recall_git, mockito$recall_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(mockito$recall_git, mockito$recall_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(mockito$measure_git, mockito$measure_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(mockito$measure_git, mockito$measure_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)


nest <- read.csv(file = paste(pathbase, "nest.csv", sep = "/"), header = TRUE, sep = ";")
summary(nest, mean, na.rm=TRUE)
sd(nest$effort_svn)
sd(nest$effort_git)
wilcox.test(nest$effort_git, nest$effort_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(nest$effort_git, nest$effort_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(nest$percentageOfChange_git, nest$percentageOfChange_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(nest$percentageOfChange_git, nest$percentageOfChange_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(nest$accuracy_git, nest$accuracy_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(nest$accuracy_git, nest$accuracy_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(nest$precision_git, nest$precision_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(nest$precision_git, nest$precision_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(nest$recall_git, nest$recall_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(nest$recall_git, nest$recall_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(nest$measure_git, nest$measure_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(nest$measure_git, nest$measure_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)


netdata <- read.csv(file = paste(pathbase, "netdata.csv", sep = "/"), header = TRUE, sep = ";")
summary(netdata, mean, na.rm=TRUE)
sd(netdata$effort_svn)
sd(netdata$effort_git)
wilcox.test(netdata$effort_git, netdata$effort_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(netdata$effort_git, netdata$effort_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(netdata$percentageOfChange_git, netdata$percentageOfChange_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(netdata$percentageOfChange_git, netdata$percentageOfChange_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(netdata$accuracy_git, netdata$accuracy_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(netdata$accuracy_git, netdata$accuracy_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(netdata$precision_git, netdata$precision_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(netdata$precision_git, netdata$precision_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(netdata$recall_git, netdata$recall_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(netdata$recall_git, netdata$recall_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(netdata$measure_git, netdata$measure_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(netdata$measure_git, netdata$measure_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)


netty <- read.csv(file = paste(pathbase, "netty.csv", sep = "/"), header = TRUE, sep = ";")
summary(netty, mean, na.rm=TRUE)
sd(netty$effort_svn)
sd(netty$effort_git)
wilcox.test(netty$effort_git, netty$effort_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(netty$effort_git, netty$effort_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(netty$percentageOfChange_git, netty$percentageOfChange_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(netty$percentageOfChange_git, netty$percentageOfChange_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(netty$accuracy_git, netty$accuracy_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(netty$accuracy_git, netty$accuracy_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(netty$precision_git, netty$precision_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(netty$precision_git, netty$precision_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(netty$recall_git, netty$recall_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(netty$recall_git, netty$recall_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(netty$measure_git, netty$measure_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(netty$measure_git, netty$measure_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)


obs_studio <- read.csv(file = paste(pathbase, "obs-studio.csv", sep = "/"), header = TRUE, sep = ";")
summary(obs_studio, mean, na.rm=TRUE)
sd(obs_studio$effort_svn)
sd(obs_studio$effort_git)
wilcox.test(obs_studio$effort_git, obs_studio$effort_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(obs_studio$effort_git, obs_studio$effort_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(obs_studio$percentageOfChange_git, obs_studio$percentageOfChange_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(obs_studio$percentageOfChange_git, obs_studio$percentageOfChange_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(obs_studio$accuracy_git, obs_studio$accuracy_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(obs_studio$accuracy_git, obs_studio$accuracy_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(obs_studio$precision_git, obs_studio$precision_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(obs_studio$precision_git, obs_studio$precision_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(obs_studio$recall_git, obs_studio$recall_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(obs_studio$recall_git, obs_studio$recall_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(obs_studio$measure_git, obs_studio$measure_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(obs_studio$measure_git, obs_studio$measure_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)


openssl <- read.csv(file = paste(pathbase, "openssl.csv", sep = "/"), header = TRUE, sep = ";")
summary(openssl, mean, na.rm=TRUE)
sd(openssl$effort_svn)
sd(openssl$effort_git)
wilcox.test(openssl$effort_git, openssl$effort_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(openssl$effort_git, openssl$effort_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(openssl$percentageOfChange_git, openssl$percentageOfChange_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(openssl$percentageOfChange_git, openssl$percentageOfChange_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(openssl$accuracy_git, openssl$accuracy_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(openssl$accuracy_git, openssl$accuracy_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(openssl$precision_git, openssl$precision_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(openssl$precision_git, openssl$precision_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(openssl$recall_git, openssl$recall_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(openssl$recall_git, openssl$recall_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(openssl$measure_git, openssl$measure_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(openssl$measure_git, openssl$measure_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)


pandas <- read.csv(file = paste(pathbase, "pandas.csv", sep = "/"), header = TRUE, sep = ";")
summary(pandas, mean, na.rm=TRUE)
sd(pandas$effort_svn)
sd(pandas$effort_git)
wilcox.test(pandas$effort_git, pandas$effort_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(pandas$effort_git, pandas$effort_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(pandas$percentageOfChange_git, pandas$percentageOfChange_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(pandas$percentageOfChange_git, pandas$percentageOfChange_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(pandas$accuracy_git, pandas$accuracy_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(pandas$accuracy_git, pandas$accuracy_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(pandas$precision_git, pandas$precision_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(pandas$precision_git, pandas$precision_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(pandas$recall_git, pandas$recall_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(pandas$recall_git, pandas$recall_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(pandas$measure_git, pandas$measure_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(pandas$measure_git, pandas$measure_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)


protobuf <- read.csv(file = paste(pathbase, "protobuf.csv", sep = "/"), header = TRUE, sep = ";")
summary(protobuf, mean, na.rm=TRUE)
sd(protobuf$effort_svn)
sd(protobuf$effort_git)
wilcox.test(protobuf$effort_git, protobuf$effort_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(protobuf$effort_git, protobuf$effort_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(protobuf$percentageOfChange_git, protobuf$percentageOfChange_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(protobuf$percentageOfChange_git, protobuf$percentageOfChange_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(protobuf$accuracy_git, protobuf$accuracy_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(protobuf$accuracy_git, protobuf$accuracy_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(protobuf$precision_git, protobuf$precision_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(protobuf$precision_git, protobuf$precision_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(protobuf$recall_git, protobuf$recall_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(protobuf$recall_git, protobuf$recall_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(protobuf$measure_git, protobuf$measure_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(protobuf$measure_git, protobuf$measure_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)


react <- read.csv(file = paste(pathbase, "react.csv", sep = "/"), header = TRUE, sep = ";")
summary(react, mean, na.rm=TRUE)
sd(react$effort_svn)
sd(react$effort_git)
wilcox.test(react$effort_git, react$effort_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(react$effort_git, react$effort_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(react$percentageOfChange_git, react$percentageOfChange_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(react$percentageOfChange_git, react$percentageOfChange_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(react$accuracy_git, react$accuracy_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(react$accuracy_git, react$accuracy_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(react$precision_git, react$precision_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(react$precision_git, react$precision_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(react$recall_git, react$recall_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(react$recall_git, react$recall_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(react$measure_git, react$measure_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(react$measure_git, react$measure_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)


redis <- read.csv(file = paste(pathbase, "redis.csv", sep = "/"), header = TRUE, sep = ";")
summary(redis, mean, na.rm=TRUE)
sd(redis$effort_svn)
sd(redis$effort_git)
wilcox.test(redis$effort_git, redis$effort_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(redis$effort_git, redis$effort_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(redis$percentageOfChange_git, redis$percentageOfChange_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(redis$percentageOfChange_git, redis$percentageOfChange_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(redis$accuracy_git, redis$accuracy_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(redis$accuracy_git, redis$accuracy_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(redis$precision_git, redis$precision_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(redis$precision_git, redis$precision_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(redis$recall_git, redis$recall_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(redis$recall_git, redis$recall_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(redis$measure_git, redis$measure_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(redis$measure_git, redis$measure_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)


redux <- read.csv(file = paste(pathbase, "redux.csv", sep = "/"), header = TRUE, sep = ";")
summary(redux, mean, na.rm=TRUE)
sd(redux$effort_svn)
sd(redux$effort_git)
wilcox.test(redux$effort_git, redux$effort_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(redux$effort_git, redux$effort_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(redux$percentageOfChange_git, redux$percentageOfChange_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(redux$percentageOfChange_git, redux$percentageOfChange_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(redux$accuracy_git, redux$accuracy_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(redux$accuracy_git, redux$accuracy_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(redux$precision_git, redux$precision_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(redux$precision_git, redux$precision_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(redux$recall_git, redux$recall_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(redux$recall_git, redux$recall_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(redux$measure_git, redux$measure_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(redux$measure_git, redux$measure_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)


requests <- read.csv(file = paste(pathbase, "requests.csv", sep = "/"), header = TRUE, sep = ";")
summary(requests, mean, na.rm=TRUE)
sd(requests$effort_svn)
sd(requests$effort_git)
wilcox.test(requests$effort_git, requests$effort_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(requests$effort_git, requests$effort_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(requests$percentageOfChange_git, requests$percentageOfChange_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(requests$percentageOfChange_git, requests$percentageOfChange_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(requests$accuracy_git, requests$accuracy_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(requests$accuracy_git, requests$accuracy_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(requests$precision_git, requests$precision_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(requests$precision_git, requests$precision_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(requests$recall_git, requests$recall_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(requests$recall_git, requests$recall_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(requests$measure_git, requests$measure_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(requests$measure_git, requests$measure_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)


retrofit <- read.csv(file = paste(pathbase, "retrofit.csv", sep = "/"), header = TRUE, sep = ";")
summary(retrofit, mean, na.rm=TRUE)
sd(retrofit$effort_svn)
sd(retrofit$effort_git)
wilcox.test(retrofit$effort_git, retrofit$effort_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(retrofit$effort_git, retrofit$effort_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(retrofit$percentageOfChange_git, retrofit$percentageOfChange_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(retrofit$percentageOfChange_git, retrofit$percentageOfChange_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(retrofit$accuracy_git, retrofit$accuracy_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(retrofit$accuracy_git, retrofit$accuracy_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(retrofit$precision_git, retrofit$precision_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(retrofit$precision_git, retrofit$precision_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(retrofit$recall_git, retrofit$recall_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(retrofit$recall_git, retrofit$recall_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(retrofit$measure_git, retrofit$measure_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(retrofit$measure_git, retrofit$measure_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)


scrapy <- read.csv(file = paste(pathbase, "scrapy.csv", sep = "/"), header = TRUE, sep = ";")
summary(scrapy, mean, na.rm=TRUE)
sd(scrapy$effort_svn)
sd(scrapy$effort_git)
wilcox.test(scrapy$effort_git, scrapy$effort_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(scrapy$effort_git, scrapy$effort_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(scrapy$percentageOfChange_git, scrapy$percentageOfChange_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(scrapy$percentageOfChange_git, scrapy$percentageOfChange_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(scrapy$accuracy_git, scrapy$accuracy_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(scrapy$accuracy_git, scrapy$accuracy_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(scrapy$precision_git, scrapy$precision_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(scrapy$precision_git, scrapy$precision_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(scrapy$recall_git, scrapy$recall_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(scrapy$recall_git, scrapy$recall_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(scrapy$measure_git, scrapy$measure_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(scrapy$measure_git, scrapy$measure_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)


scrcpy <- read.csv(file = paste(pathbase, "scrcpy.csv", sep = "/"), header = TRUE, sep = ";")
summary(scrcpy, mean, na.rm=TRUE)
sd(scrcpy$effort_svn)
sd(scrcpy$effort_git)
wilcox.test(scrcpy$effort_git, scrcpy$effort_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(scrcpy$effort_git, scrcpy$effort_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(scrcpy$percentageOfChange_git, scrcpy$percentageOfChange_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(scrcpy$percentageOfChange_git, scrcpy$percentageOfChange_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(scrcpy$accuracy_git, scrcpy$accuracy_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(scrcpy$accuracy_git, scrcpy$accuracy_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(scrcpy$precision_git, scrcpy$precision_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(scrcpy$precision_git, scrcpy$precision_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(scrcpy$recall_git, scrcpy$recall_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(scrcpy$recall_git, scrcpy$recall_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(scrcpy$measure_git, scrcpy$measure_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(scrcpy$measure_git, scrcpy$measure_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)


socket <- read.csv(file = paste(pathbase, "socket.io.csv", sep = "/"), header = TRUE, sep = ";")
summary(socket, mean, na.rm=TRUE)
sd(socket$effort_svn)
sd(socket$effort_git)
wilcox.test(socket$effort_git, socket$effort_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(socket$effort_git, socket$effort_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(socket$percentageOfChange_git, socket$percentageOfChange_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(socket$percentageOfChange_git, socket$percentageOfChange_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(socket$accuracy_git, socket$accuracy_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(socket$accuracy_git, socket$accuracy_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(socket$precision_git, socket$precision_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(socket$precision_git, socket$precision_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(socket$recall_git, socket$recall_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(socket$recall_git, socket$recall_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(socket$measure_git, socket$measure_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(socket$measure_git, socket$measure_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)


spring_boot <- read.csv(file = paste(pathbase, "spring-boot.csv", sep = "/"), header = TRUE, sep = ";")
summary(spring_boot, mean, na.rm=TRUE)
sd(spring_boot$effort_svn)
sd(spring_boot$effort_git)
wilcox.test(spring_boot$effort_git, spring_boot$effort_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(spring_boot$effort_git, spring_boot$effort_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(spring_boot$percentageOfChange_git, spring_boot$percentageOfChange_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(spring_boot$percentageOfChange_git, spring_boot$percentageOfChange_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(spring_boot$accuracy_git, spring_boot$accuracy_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(spring_boot$accuracy_git, spring_boot$accuracy_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(spring_boot$precision_git, spring_boot$precision_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(spring_boot$precision_git, spring_boot$precision_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(spring_boot$recall_git, spring_boot$recall_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(spring_boot$recall_git, spring_boot$recall_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(spring_boot$measure_git, spring_boot$measure_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(spring_boot$measure_git, spring_boot$measure_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)


spring_framework <- read.csv(file = paste(pathbase, "spring-framework.csv", sep = "/"), header = TRUE, sep = ";")
summary(spring_framework, mean, na.rm=TRUE)
sd(spring_framework$effort_svn)
sd(spring_framework$effort_git)
wilcox.test(spring_framework$effort_git, spring_framework$effort_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(spring_framework$effort_git, spring_framework$effort_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(spring_framework$percentageOfChange_git, spring_framework$percentageOfChange_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(spring_framework$percentageOfChange_git, spring_framework$percentageOfChange_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(spring_framework$accuracy_git, spring_framework$accuracy_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(spring_framework$accuracy_git, spring_framework$accuracy_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(spring_framework$precision_git, spring_framework$precision_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(spring_framework$precision_git, spring_framework$precision_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(spring_framework$recall_git, spring_framework$recall_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(spring_framework$recall_git, spring_framework$recall_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(spring_framework$measure_git, spring_framework$measure_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(spring_framework$measure_git, spring_framework$measure_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)


terminal <- read.csv(file = paste(pathbase, "terminal.csv", sep = "/"), header = TRUE, sep = ";")
summary(terminal, mean, na.rm=TRUE)
sd(terminal$effort_svn)
sd(terminal$effort_git)
wilcox.test(terminal$effort_git, terminal$effort_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(terminal$effort_git, terminal$effort_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(terminal$percentageOfChange_git, terminal$percentageOfChange_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(terminal$percentageOfChange_git, terminal$percentageOfChange_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(terminal$accuracy_git, terminal$accuracy_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(terminal$accuracy_git, terminal$accuracy_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(terminal$precision_git, terminal$precision_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(terminal$precision_git, terminal$precision_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(terminal$recall_git, terminal$recall_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(terminal$recall_git, terminal$recall_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(terminal$measure_git, terminal$measure_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(terminal$measure_git, terminal$measure_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)


tesseract <- read.csv(file = paste(pathbase, "tesseract.csv", sep = "/"), header = TRUE, sep = ";")
summary(tesseract, mean, na.rm=TRUE)
sd(tesseract$effort_svn)
sd(tesseract$effort_git)
wilcox.test(tesseract$effort_git, tesseract$effort_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(tesseract$effort_git, tesseract$effort_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(tesseract$percentageOfChange_git, tesseract$percentageOfChange_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(tesseract$percentageOfChange_git, tesseract$percentageOfChange_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(tesseract$accuracy_git, tesseract$accuracy_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(tesseract$accuracy_git, tesseract$accuracy_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(tesseract$precision_git, tesseract$precision_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(tesseract$precision_git, tesseract$precision_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(tesseract$recall_git, tesseract$recall_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(tesseract$recall_git, tesseract$recall_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(tesseract$measure_git, tesseract$measure_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(tesseract$measure_git, tesseract$measure_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)


thefuck <- read.csv(file = paste(pathbase, "thefuck.csv", sep = "/"), header = TRUE, sep = ";")
summary(thefuck, mean, na.rm=TRUE)
sd(thefuck$effort_svn)
sd(thefuck$effort_git)
wilcox.test(thefuck$effort_git, thefuck$effort_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(thefuck$effort_git, thefuck$effort_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(thefuck$percentageOfChange_git, thefuck$percentageOfChange_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(thefuck$percentageOfChange_git, thefuck$percentageOfChange_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(thefuck$accuracy_git, thefuck$accuracy_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(thefuck$accuracy_git, thefuck$accuracy_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(thefuck$precision_git, thefuck$precision_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(thefuck$precision_git, thefuck$precision_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(thefuck$recall_git, thefuck$recall_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(thefuck$recall_git, thefuck$recall_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(thefuck$measure_git, thefuck$measure_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(thefuck$measure_git, thefuck$measure_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)


vue <- read.csv(file = paste(pathbase, "vue.csv", sep = "/"), header = TRUE, sep = ";")
summary(vue, mean, na.rm=TRUE)
sd(vue$effort_svn)
sd(vue$effort_git)
wilcox.test(vue$effort_git, vue$effort_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(vue$effort_git, vue$effort_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(vue$percentageOfChange_git, vue$percentageOfChange_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(vue$percentageOfChange_git, vue$percentageOfChange_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(vue$accuracy_git, vue$accuracy_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(vue$accuracy_git, vue$accuracy_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(vue$precision_git, vue$precision_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(vue$precision_git, vue$precision_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(vue$recall_git, vue$recall_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(vue$recall_git, vue$recall_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(vue$measure_git, vue$measure_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(vue$measure_git, vue$measure_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)


x64dbg <- read.csv(file = paste(pathbase, "x64dbg.csv", sep = "/"), header = TRUE, sep = ";")
summary(x64dbg, mean, na.rm=TRUE)
sd(x64dbg$effort_svn)
sd(x64dbg$effort_git)
wilcox.test(x64dbg$effort_git, x64dbg$effort_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(x64dbg$effort_git, x64dbg$effort_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(x64dbg$percentageOfChange_git, x64dbg$percentageOfChange_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(x64dbg$percentageOfChange_git, x64dbg$percentageOfChange_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(x64dbg$accuracy_git, x64dbg$accuracy_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(x64dbg$accuracy_git, x64dbg$accuracy_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(x64dbg$precision_git, x64dbg$precision_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(x64dbg$precision_git, x64dbg$precision_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(x64dbg$recall_git, x64dbg$recall_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(x64dbg$recall_git, x64dbg$recall_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(x64dbg$measure_git, x64dbg$measure_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(x64dbg$measure_git, x64dbg$measure_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)


youtube_dl <- read.csv(file = paste(pathbase, "youtube-dl.csv", sep = "/"), header = TRUE, sep = ";")
summary(youtube_dl, mean, na.rm=TRUE)
sd(youtube_dl$effort_svn)
sd(youtube_dl$effort_git)
wilcox.test(youtube_dl$effort_git, youtube_dl$effort_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(youtube_dl$effort_git, youtube_dl$effort_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(youtube_dl$percentageOfChange_git, youtube_dl$percentageOfChange_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(youtube_dl$percentageOfChange_git, youtube_dl$percentageOfChange_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(youtube_dl$accuracy_git, youtube_dl$accuracy_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(youtube_dl$accuracy_git, youtube_dl$accuracy_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(youtube_dl$precision_git, youtube_dl$precision_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(youtube_dl$precision_git, youtube_dl$precision_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(youtube_dl$recall_git, youtube_dl$recall_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(youtube_dl$recall_git, youtube_dl$recall_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(youtube_dl$measure_git, youtube_dl$measure_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(youtube_dl$measure_git, youtube_dl$measure_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)


zstd <- read.csv(file = paste(pathbase, "zstd.csv", sep = "/"), header = TRUE, sep = ";")
summary(zstd, mean, na.rm=TRUE)
sd(zstd$effort_svn)
sd(zstd$effort_git)
wilcox.test(zstd$effort_git, zstd$effort_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(zstd$effort_git, zstd$effort_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(zstd$percentageOfChange_git, zstd$percentageOfChange_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(zstd$percentageOfChange_git, zstd$percentageOfChange_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(zstd$accuracy_git, zstd$accuracy_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(zstd$accuracy_git, zstd$accuracy_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(zstd$precision_git, zstd$precision_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(zstd$precision_git, zstd$precision_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(zstd$recall_git, zstd$recall_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(zstd$recall_git, zstd$recall_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
wilcox.test(zstd$measure_git, zstd$measure_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
t.test(zstd$measure_git, zstd$measure_svn, alternative = "greater", paired=TRUE, conf.int= TRUE, conf.level= 0.95, exact=F, correct=F)
